# Site settings
title: soonhankwon
url: "https://soonhankwon.github.io"
baseurl: "https://soonhankwon.github.io"
description: >
    SoonhanKwon Wiki

# My information
email: soonable@gmail.com
author: soonhankwon machine
profile: INTJ
twitter_username: soonhankwon
github_username: soonhankwon
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/soonhankwon/soonhankwon.github.io/blame/master/_wiki"
edit: "https://github.com/soonhankwon/soonhankwon.github.io/edit/master/_wiki"
issue: "https://github.com/soonhankwon/soonhankwon.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
